# This template demonstrates a steps template and how to control sequential vs. parallel steps.
# In this example, the hello1 completes before the hello2a, and hello2b steps, which run in parallel.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: staging # Important. If this is a fargate profiled namespace... it will run as a fargate pod
  name : "steps"
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  ttlStrategy:
    secondsAfterCompletion: 30
  templates:
    - name: hello-hello-hello
      steps:
        - - name: hello1
            template: whalesay
            arguments:
              parameters: [{name: message, value: "hello1"}]
        - - name: hello2a
            template: whalesay
            arguments:
              parameters: [{name: message, value: "hello2a"}]
          - name: hello2b
            template: cowsay
            arguments:
              parameters: [{name: message, value: "hello2b"}]
        - - name: hello3
              template: whalesay
              arguments:
                parameters: [ { name: message, value: "hello3" } ]

    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
    - name: cowsay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]