# This template demonstrates a steps template and how to control sequential vs. parallel steps.
# In this example, the hello1 completes before the hello2a, and hello2b steps, which run in parallel.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: staging # Important. If this is a fargate profiled namespace... it will run as a fargate pod
  name : "way4-poc"
  generateName: way4-poc-
spec:
  entrypoint: starter-job
  ttlStrategy:
    secondsAfterCompletion: 60
  templates:
    - name: starter-job
      steps:
        -
          - name: main-jobs-parallel
            template: main-jobs
            arguments:
              parameters: [{name: message, value: "starter-job"}]


    - name: main-jobs
      steps:
        -
          - name: ops-preworks-sequential
            template: ops-preworks-jobs
            arguments:
              parameters: [{name: message, value: "ops-preworks"}]
          - name: auth-parser-batch-p3-parallel
            template: auth-parser-batch-p3-jobs
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-p3"}]
          - name: pgfs-group-sequential
            template: pgfs-jobs
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-p3"}]
          - name: auth-parser-group-sequential
            template: auth-parser-jobs
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-p3"}]
          - name: cms-file-transfer-upload-dag
              template: cms-file-transfer-upload
              arguments:
                parameters: [{name: message, value: "auth-parser-batch-p3"}]

    - name: cms-file-transfer-upload
      dag:
        tasks:
          - name: cms-file-transfer-upload
            template: whalesay
            dependencies: [ops-preworks-jobs]
            arguments:
              parameters: [{name: message, value: "cms-file-transfer-upload"}]


    - name: ops-preworks-jobs
      steps:
        -
          - name: mc-file-transfer-files-inc-migs
            template: whalesay
            arguments:
              parameters: [{name: message, value: "mc-file-transfer-files-inc-migs"}]
        -
          - name: way4-dcf-parser-transfer
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-dcf-parser-transfer"}]
        -
          - name: way4-dcf-authorization-parser
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-dcf-authorization-parser"}]
        -
          - name: visa-file-transfer-files-inc-ctv
            template: whalesay
            arguments:
              parameters: [{name: message, value: "visa-file-transfer-files-inc-ctv"}]
        -
          - name: way4-ctv-parser-transfer
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-ctv-parser-transfer"}]
        -
          - name: way4-ctv-authorization-parser
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-ctv-authorization-parser"}]

    - name: auth-parser-batch-p3-jobs
      steps:
        -
          - name: way4-doc-generation-p3-visa
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-doc-generation-p3-visa"}]
          - name: way4-doc-generation-p3-mc
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-doc-generation-p3-mc"}]
          - name: way4-doc-generation-p3-jcb
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-doc-generation-p3-jcb"}]
          - name: way4-doc-generation-p3-amex
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-doc-generation-p3-amex"}]
          - name: way4-doc-generation-bancnet
            template: whalesay
            arguments:
              parameters: [{name: message, value: "way4-doc-generation-bancnet"}]

    - name: pgfs-jobs
      steps:
        -
          - name: transfer-pgfs-files
            template: whalesay
            arguments:
              parameters: [{name: message, value: "transfer-pgfs-files"}]
        -
          - name: auth-parser-batch-pgfs
            template: whalesay
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-pgfs"}]

    - name: auth-parser-jobs
      steps:
        -
          - name: auth-parser-batch-paypal
            template: whalesay
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-paypal"}]
        -
          - name: auth-parser-batch-mdms
            template: whalesay
            arguments:
              parameters: [{name: message, value: "auth-parser-batch-mdms"}]

# actual template running
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
